import { ResourceType } from "../enums/resource-type.enum";
import { Daemon } from "../models/daemon.model";

export const availableDaemons: Array<Daemon> = [
    {
      id: 0,
      life: 10,
      inputAmount: 2,
      inputResource: ResourceType.BinaryCodes,
      outputAmount: 1,
      outputResource: ResourceType.CriptoCoins,
      efficiency: 1,
      cycleTime: 10000,
      cost: 1000,
      progress: 0,
      isRunning: false,
      isPaused: false,
    },  
    {
      id: 0,
      life: 10,
      inputAmount: 5,
      inputResource: ResourceType.CriptoCoins,
      outputAmount: 1,
      outputResource: ResourceType.DataPackets,
      efficiency: 1,
      cycleTime: 2000,
      cost: 200,
      progress: 0,
      isRunning: false,
      isPaused: false,
    },
    {
      id: 0,
      life: 10,
      inputAmount: 10,
      inputResource: ResourceType.DataPackets,
      outputAmount: 1,
      outputResource: ResourceType.MemoryBlocks,
      efficiency: 1,
      cycleTime: 8000,
      cost: 400,
      progress: 0,
      isRunning: false,
      isPaused: false,
    },
  ];